# Generated by Django 3.2.13 on 2022-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
