# Generated by Django 4.0.5 on 2022-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_completed',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
